name: 'Trigger: Push'

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run checks
      run:  echo "==> Running some basic checks"
    - name: Shellcheck
      uses: ludeeus/action-shellcheck@0.1.0
